### ISSUE TITLE
How is this different from Mozilla A-Frame and react-aframe?

### ISSUE THREAD

**Issue by mbylstra** [facebookincubator/react-vr#18]
This seems very similar from a-frame which is also declarative wrapper on top of three.js. What are the benefits of this package and are the benefits significant enough that they couldn't be just be contributed to a-frame? There is an ecosystem of packages on top of a-frame that would need to be ported.

**Comment by borisyankov** [comment]
'declarative wrapper' sounds like an understatement.
Three.js is the rendering 'layer' but React/ReactVR do much more than wrap a library.

a-frame is fundamentally different than react-vr.
Just as there are angular.js, ember, react you should expect multiple VR authoring approaches to exist.

**Comment by mbylstra** [comment]
Can you explain the advantage over aframe-react?

**Comment by amberroy** [comment]
Here's what I see as the main differences, having written apps in both A-Frame and React VR.  
* React VR apps are written in JavaScript, with JSX tags that are transpiled into JS.  A-Frame apps use HTML, with custom HTML tags (whether this is advantage or disadvantage depends if you want to code in JS or HTML :) although A-Frame components are built with JavaScript.
* React VR is based on the React core (in production use since 2011, open sourced in 2013) and A-Frame is written from scratch (mid-to-late 2015).  So contributing back to a-frame is not possible since they have different underlying implementations.
* React VR is build on top of React Native, with a JS runtime for WebVR, while aframe-react is a very thin layer on top of A-Frame to bridge with React JS.

**Comment by mikearmstrong001** [comment]
To add, having access to flexbox based layout within React VR shouldn't be underestimated when defining dynamic or UIs that need that little bit of iteration to get right. Layout is often forgotten but very important.
