### ISSUE TITLE
CSS3D Renderer?

### ISSUE THREAD

**Issue by ElliotChong** [facebookincubator/react-vr#34]
### Description

Any plans to support a CSS3D-based renderer so that content creators can use HTML to create UIs?

There is [an old renderer written by @mrdoob](https://github.com/mrdoob/three.js/issues/7309) ([code found elsewhere since it's no longer in the Three.js repo](https://github.com/Colmea/react-three-renderer-html3d/blob/master/library/CSS3DRenderer.js)) that still works today and could be used in concert with a typical Three.JS scene. It ignores any entities which aren't of type `THREE.CSS3DObject` so you can intermingle them with your standard `THREE.Object3D` objects in a single scene.

Some issues that come to mind that would need to be tackled:
* Stereoscopic rendering would need to output two DOMs - one for each camera. Given that we have a nice virtual DOM courtesy of React this should be solvable at the vDOM -> browser DOM layer.
* z-depth and occlusion could be solved by wrapping each `THREE.CSS3DObject` in a `THREE.Object3D` container which contains the DOM element and a mirroring `Plane`* with its blending set to `THREE.NoBlending`. This would effectively create a properly z-sorted occlusion of the CSS3D content. All transformations would be applied to the wrapper `THREE.Object3D` container. (*NOTE: Occlusion would only appear correct for rectangular content- extra considerations would need to be made for content with rounded corners for instance.)
* User interaction- To support common DOM events the CSS3D renderer/s should be placed on top of the WebGL `canvas`. You could then use the `capture` phase of the CSS3D renderer's `div` to proxy and redispatch the event into the `canvas`. If the event wouldn't have hit the occlusion plane then the original event can be canceled and prevent propagation into the regular DOM content. There may need to be some special consideration for how this would work in the stereo-DOM scenario... For instance, you could proxy the event into the duplicate DOM to allow CSS-based `[hover]` interactions; however, you'd need to ensure only one of the renderers executes JS-based callbacks so that there aren't undesirable side-effects such as double-execution.

I'm assuming this wouldn't be a near-term feature for ReactVR, but curious if it's on the road map and how desirable the feature is.

Thanks!

**Comment by andrewimm** [comment]
A CSS renderer wouldn't be able to draw to a VR Headset through the WebVR APIs, which is the chief goal of React VR, and the multiple layers of abstraction within the browser engine would make it far slower than direct GPU rendering.

Keep in mind that React VR is not a generic React -> 3d renderer. There are already libraries out there that can render React components to Three scenes (I've written a couple myself). React VR is targeted at building UIs and scenes for VR headsets, and providing a simpler path to VR development than a native Unity / Unreal application.

While a CSS renderer is not something we're going to pursue, we definitely agree with the value in having DOM elements render directly to canvas where possible. There are some proposals being worked out by browser vendors that would allow HTML nodes to be rendered to textures, and then used within a WebGL scene. This type of functionality, if developed, would allow quick layout and easy-to-manipulate panels within your world, but unfortunately we're not there yet from a technical perspective. If html-to-texture rendering does come about, we'll probably integrate it into the web version of React VR.

Closing, since a CSS renderer will not be part of React VR.

**Comment by ElliotChong** [comment]
Thanks @andrewimm!
