### ISSUE TITLE
[Question] How can I get involved in the project?

### ISSUE THREAD

**Issue by tomaszlakomygp** [facebookincubator/react-vr#51]
I guess the title says it all :) Since the project is not yet open source and I'm quite passionate about it, is there anything I can do to help? I'd love to submit some PRs once react-vr is open sourced etc.

**Comment by amberroy** [comment]
This is my favorite 'issue' so far haha.   I will get the answer for you, and also add it to our README.md since other have asked.

**Comment by mikearmstrong001** [comment]
I don't have a firm date for Open Source just yet and we'll provide more information as soon as we can. 
I admit the timeline did get pushed back a bit further than we originally intended due to priorities but we are hoping that the reasonably regular npm updates give insight into where the project is developing.
And thanks for your interest as soon as we have everything in place on GitHub we will be gladly accepting PRs, this is exactly why we are going this direction:)
And sorry for the non confirmation of a GitHub date.

**Comment by tomaszlakomygp** [comment]
No worries, thanks for the reply and keep up the good work!
