### ISSUE TITLE
Any chance to make it work with React-Native and google cardboard?

### ISSUE THREAD

**Issue by rborn** [facebookincubator/react-vr#58]
Thank you 😄

**Comment by tomaszlakomygp** [comment]
I know that there were some attempts to make React-VR run on a google cardboard but I'm not sure if it worked after all, I'm interested too

**Comment by rborn** [comment]
@tomaszlakomygp there are few repos that only implement the video/panorama, but nothing related to interaction or custom views (text, etc) 😞

**Comment by tomaszlakomygp** [comment]
@rborn Could you link me to those repos? I'd love to take a look and play with them a bit

**Comment by rborn** [comment]
- https://github.com/tiero/react-native-360
- https://github.com/cnspica/react-native-vr (this has nothing in it sadly and made me thing there are more repos 😞 )
- http://www.discoveryvr.com - seems to be made with react-native but is not opensource

Let me know if you find anything else 😄

**Comment by rborn** [comment]
- https://github.com/XebiaStudio/react-native-google-vr-panorama

**Comment by iamkyleee** [comment]
I'm in the same situation. Just imagine the possibilities of having RN VR 😮

**Comment by amberroy** [comment]
Sorry no plans to make React VR compatible with React Native or google cardboard.

**Comment by andrewimm** [comment]
As Amber notes, we're not looking to support alternative rendering methods like Cardboard.
React VR aims to be the way to build best-in-class VR experiences on the web, on devices that support real VR APIs. We're just a bit ahead of the curve here, in that support for WebVR is still a bit immature.

While we might not support "cardboard" in the more abstract sense of rendering two warped eye views on the screen, we **do** support Daydream (the future of cardboard at Google). Chrome for Android 56 ships with support for WebVR, and if you launch it on a phone running Android N, you'll get a full VR experience. If you own a Daydream headset (like the Daydream View), it will launch with Google's Daydream APIs. If you don't, or if your phone is not compatible with one, it will launch with the traditional Cardboard APIs, and you can use your phone in any headset. We expect that this will be the future of VR on mobile, and are skating to where the puck will be in the next 6-12 months.

**Comment by larrySigo** [comment]
Please does react vr support meteorjs n which other headset is supported by react vr bcos am thinking of getting one that works with my iPhone

**Comment by alessandro-aglietti** [comment]
@andrewimm could be useful if the react-360 docs will have a dedicated section that explain this positioning about WebVR and how/which is the suggested way to test the VR mode.
Can be a simple guide like the webvr site [1] one.

In my case, I digging an hour before know that react 360 show an automagic :) button "View in VR"  **if** the device support WebVR instead of showing classic carboard button also on device that didn't support WebVR.
And then I spent more time to understand that exists an extension[2] useful to get the VR mode using desktop browser without dedicated hardware.

[1] https://webvr.info/developers/
[2] https://chrome.google.com/webstore/detail/webvr-api-emulation/gbdnpaebafagioggnhkacnaaahpiefil
